#!/bin/bash
# Use ./build web to build just web module and deploy, ./build core to build core, than web and deploy.

#export JAVA_OPTIONS="-Dhttp.proxyHost=proxy2.cht -Dhttp.proxyPort=3128:$JAVA_FLAGS"

if [[ $JAVA_HOME != *jdk1.8* ]]; then
    export JAVA_HOME=/home/yaroslav/usr/jdk1.8.0_05
    export PATH="$JAVA_HOME/bin:$PATH"
fi

GLASSFISH=/home/yaroslav/usr/latest-glassfish4/bin/asadmin
ARTIFACT_PATH=/home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
ARTIFACT_NAME=web-1.0-SNAPSHOT
CONTEXT_ROOT=lingvo-movie
CORE=core
WEB=web
PARSER=parser
TRANSLATOR=translator

ARG=$1

if [[ $ARG = "web" ]]; then
    mvn -f $WEB/pom.xml clean install
fi

if [[ $ARG = "deploy" ]]; then
    sh $GLASSFISH deploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
    exit
fi

if [[ $ARG = "redeploy" ]]; then
    sh $GLASSFISH redeploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
    exit
fi

if [[ $ARG = "core" ]]; then
    mvn -f $CORE/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f $WEB/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh $GLASSFISH redeploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
        fi
    fi
        exit
fi

if [[ $ARG = "parser" ]]; then
    mvn -f $PARSER/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f $WEB/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh $GLASSFISH redeploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
        fi
    fi
        exit
fi

if [[ $ARG = "translator" ]]; then
    mvn -f translator/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f $WEB/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh $GLASSFISH redeploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
        fi
    fi
        exit
fi


if [ $# -eq 0 ]; then
    mvn clean install
fi

STATUS=$?
if [ $STATUS -eq 0 ]; then
sh $GLASSFISH redeploy --name $ARTIFACT_NAME --contextroot $CONTEXT_ROOT $ARTIFACT_PATH
fi

