#!/bin/bash
# Use ./build web to build just web module and deploy, ./build core to build core, than web and deploy.

#export JAVA_OPTIONS="-Dhttp.proxyHost=proxy2.cht -Dhttp.proxyPort=3128:$JAVA_FLAGS"

if [[ $JAVA_HOME != *jdk1.8* ]]; then
    export JAVA_HOME=/home/yaroslav/usr/jdk1.8.0_05
    export PATH="$JAVA_HOME/bin:$PATH"
fi

GLASSFISH='sh /home/yaroslav/usr/soft/glassfish4/bin/asadmin'

PROJECT_FOLDER=/home/yaroslav/workspace/LearnEnglishProject/LearnEnglishWithMovies

REST_SERVICE_ARTIFACT_PATH=$PROJECT_FOLDER/core/target/core-1.0-SNAPSHOT.war
REST_SERVICE_ARTIFACT_NAME=core-lingvo-1.0
REST_SERVICE_CONTEXT_ROOT=lingvo-movie-core

WEB_ARTIFACT_PATH=$PROJECT_FOLDER/web/target/web-1.0-SNAPSHOT.war
WEB_ARTIFACT_NAME=web-lingvo-1.0
WEB_CONTEXT_ROOT=lingvo-movie

CORE=core
WEB=web
PARSER=parser
TRANSLATOR=translator

ARG=$1

if [[ $ARG = "web" ]]; then
    mvn -f $WEB/pom.xml clean install
    STATUS=$?
    if [ $STATUS -eq 0 ]; then
        $GLASSFISH deploy --force=true --name $WEB_ARTIFACT_NAME --contextroot $WEB_CONTEXT_ROOT $WEB_ARTIFACT_PATH
    fi
    exit
fi

if [[ $ARG = "core" ]]; then
    mvn -f $CORE/pom.xml clean install
    STATUS=$?
    if [ $STATUS -eq 0 ]; then
        $GLASSFISH deploy --force=true --name $REST_SERVICE_ARTIFACT_NAME --contextroot $REST_SERVICE_CONTEXT_ROOT $REST_SERVICE_ARTIFACT_PATH
    fi
    exit
fi

if [[ $ARG = "redeploy" ]]; then
    $GLASSFISH deploy --force=true --name $REST_SERVICE_ARTIFACT_NAME --contextroot $REST_SERVICE_CONTEXT_ROOT $REST_SERVICE_ARTIFACT_PATH
     sh $GLASSFISH deploy --force=true --name $WEB_ARTIFACT_NAME --contextroot $WEB_CONTEXT_ROOT $WEB_ARTIFACT_PATH
    exit
fi


if [ $# -eq 0 ]; then
    mvn clean install
fi

STATUS=$?
if [ $STATUS -eq 0 ]; then
     $GLASSFISH deploy --force=true --name $REST_SERVICE_ARTIFACT_NAME --contextroot $REST_SERVICE_CONTEXT_ROOT $REST_SERVICE_ARTIFACT_PATH
     $GLASSFISH deploy --force=true --name $WEB_ARTIFACT_NAME --contextroot $WEB_CONTEXT_ROOT $WEB_ARTIFACT_PATH
fi

