#!/bin/bash
# Use ./build web to build just web module and deploy, ./build core to build core, than web and deploy.

if [[ $JAVA_HOME != *jdk1.8* ]]; then
    export JAVA_HOME=/home/yaroslav/usr/jdk1.8.0_05
    export PATH="$JAVA_HOME/bin:$PATH"
fi

ARG=$1

if [[ $ARG = "web" ]]; then
    mvn -f web/pom.xml clean install
fi

if [[ $ARG = "deploy" ]]; then
    sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin deploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
    exit
fi

if [[ $ARG = "redeploy" ]]; then
    sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin redeploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
    exit
fi

if [[ $ARG = "core" ]]; then
    mvn -f core/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f web/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin redeploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
        fi
    fi
        exit
fi

if [[ $ARG = "parser" ]]; then
    mvn -f parser/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f web/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin redeploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
        fi
    fi
        exit
fi

if [[ $ARG = "translator" ]]; then
    mvn -f translator/pom.xml clean install
    STATUS1=$?
    if [ $STATUS1 -eq 0 ]; then
        mvn -f web/pom.xml clean install

        STATUS=$?
        if [ $STATUS -eq 0 ]; then
            sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin redeploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
        fi
    fi
        exit
fi


if [ $# -eq 0 ]; then
    mvn clean install
fi

STATUS=$?
if [ $STATUS -eq 0 ]; then
sh /home/yaroslav/usr/latest-glassfish4/bin/asadmin redeploy --name web-1.0-SNAPSHOT /home/yaroslav/workspace/LearnEnglishWithMovies/web/target/web-1.0-SNAPSHOT.war
fi

