#!/bin/bash
curl -s -S \
    --user admin:admin \
    --insecure \
    -H "Accept: application/json" \
    -H "X-Requested-By: dummy" \
    -X POST \
    -F id=@/home/yaroslav/workspace/LearnEnglishWithMovies/learn-english-web/target/learn-english-web-1.0-SNAPSHOT.war \
    -F force=true \
    https://192.168.32.242:4848/management/domain/applications/application
